const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // ── libteru (core library, pure Zig, no system deps) ─────────────
    const lib_mod = b.createModule(.{
        .root_source_file = b.path("src/lib.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    const lib = b.addLibrary(.{
        .name = "teru",
        .root_module = lib_mod,
    });
    b.installArtifact(lib);

    // ── Platform backend options ───────────────────────────────────
    // -Dx11=false     → build Wayland-only (no libxcb dependency)
    // -Dwayland=false → build X11-only (no libwayland dependency)
    // Both default to true for the standard dual-backend binary.
    const enable_x11 = b.option(bool, "x11", "Enable X11 backend (default: true)") orelse true;
    const enable_wayland = b.option(bool, "wayland", "Enable Wayland backend (default: true)") orelse true;

    if (!enable_x11 and !enable_wayland) {
        std.debug.print("error: at least one of -Dx11 or -Dwayland must be enabled\n", .{});
        @panic("no platform backend selected");
    }

    // Build-time options passed to Zig source via @import("build_options")
    const build_options = b.addOptions();
    build_options.addOption(bool, "enable_x11", enable_x11);
    build_options.addOption(bool, "enable_wayland", enable_wayland);

    // ── teru executable ──────────────────────────────────────────────
    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });

    exe_mod.addOptions("build_options", build_options);

    // System dependencies: link only the enabled backends
    // xkbcommon is needed for both X11 and Wayland keyboard translation
    if (enable_x11 or enable_wayland) {
        exe_mod.linkSystemLibrary("xkbcommon", .{});
    }
    if (enable_x11) {
        exe_mod.linkSystemLibrary("xcb", .{});
        exe_mod.linkSystemLibrary("xcb-shm", .{});
    }
    if (enable_wayland) {
        exe_mod.linkSystemLibrary("wayland-client", .{});

        // Vendored: xdg-shell protocol (generated by wayland-scanner)
        exe_mod.addCSourceFile(.{
            .file = b.path("vendor/xdg-shell-protocol.c"),
            .flags = &.{},
        });
    }

    // Embedded: stb_truetype (compiled from vendored source)
    exe_mod.addCSourceFile(.{
        .file = b.path("vendor/stb_truetype.c"),
        .flags = &.{"-DSTB_TRUETYPE_IMPLEMENTATION"},
    });
    exe_mod.addIncludePath(b.path("vendor"));

    const exe = b.addExecutable(.{
        .name = "teru",
        .root_module = exe_mod,
    });
    b.installArtifact(exe);

    // ── run step ─────────────────────────────────────────────────────
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }
    const run_step = b.step("run", "Run teru terminal");
    run_step.dependOn(&run_cmd.step);

    // ── tests (pure Zig, no system deps needed) ──────────────────────
    const test_mod = b.createModule(.{
        .root_source_file = b.path("src/lib.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    const lib_tests = b.addTest(.{
        .root_module = test_mod,
    });
    const run_lib_tests = b.addRunArtifact(lib_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_lib_tests.step);
}
