const std = @import("std");

pub fn build(b: *std.Build) void {
    const target = b.standardTargetOptions(.{});
    const optimize = b.standardOptimizeOption(.{});

    // ── Single source of truth for version ────────────────────────
    // Propagated to all modules via build_options.version.
    // Bump with: make bump-version V=x.y.z (updates here + build.zig.zon)
    const version = "0.6.3";

    // ── libteru (core library, pure Zig, no system deps) ─────────────
    const lib_mod = b.createModule(.{
        .root_source_file = b.path("src/lib.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    // Vendor include path for hand-declared C bindings (stb_truetype, xdg-shell, miozu-wlr-glue).
    lib_mod.addIncludePath(b.path("vendor"));

    const lib = b.addLibrary(.{
        .name = "teru",
        .root_module = lib_mod,
    });
    b.installArtifact(lib);

    // ── Resolved target OS ─────────────────────────────────────────
    const os_tag = target.result.os.tag;

    // ── Platform backend options ───────────────────────────────────
    // -Dx11=false     → build Wayland-only (no libxcb dependency)
    // -Dwayland=false → build X11-only (no libwayland dependency)
    // Both default to true for the standard dual-backend binary.
    // On non-Linux, these default to false (X11/Wayland are Linux-only).
    const enable_x11 = b.option(bool, "x11", "Enable X11 backend (default: true on Linux)") orelse (os_tag == .linux);
    const enable_wayland = b.option(bool, "wayland", "Enable Wayland backend (default: true on Linux)") orelse (os_tag == .linux);

    if (os_tag == .linux and !enable_x11 and !enable_wayland) {
        std.debug.print("error: at least one of -Dx11 or -Dwayland must be enabled\n", .{});
        @panic("no platform backend selected");
    }

    // ── Compositor option ──────────────────────────────────────────
    // -Dcompositor=true → build miozu Wayland compositor (links wlroots)
    const enable_compositor = b.option(bool, "compositor", "Build miozu Wayland compositor (links wlroots)") orelse false;

    // Build-time options passed to Zig source via @import("build_options")
    const build_options = b.addOptions();
    build_options.addOption([]const u8, "version", version);
    build_options.addOption(bool, "enable_x11", enable_x11);
    build_options.addOption(bool, "enable_wayland", enable_wayland);
    build_options.addOption(bool, "enable_compositor", enable_compositor);

    // Attach build_options to library module (needed by McpServer.zig)
    lib_mod.addOptions("build_options", build_options);

    // ── teru executable ──────────────────────────────────────────────
    const exe_mod = b.createModule(.{
        .root_source_file = b.path("src/main.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });

    exe_mod.addOptions("build_options", build_options);

    // ── Platform-specific system dependencies ──────────────────────
    if (os_tag == .linux) {
        // xkbcommon is needed for both X11 and Wayland keyboard translation
        if (enable_x11 or enable_wayland) {
            exe_mod.linkSystemLibrary("xkbcommon", .{});
        }
        if (enable_x11) {
            exe_mod.linkSystemLibrary("xcb", .{});
            exe_mod.linkSystemLibrary("xcb-shm", .{});
        }
        if (enable_wayland) {
            exe_mod.linkSystemLibrary("wayland-client", .{});

            // Vendored: xdg-shell protocol (generated by wayland-scanner)
            exe_mod.addCSourceFile(.{
                .file = b.path("vendor/xdg-shell-protocol.c"),
                .flags = &.{},
            });
        }
    } else if (os_tag == .macos) {
        exe_mod.linkFramework("AppKit", .{});
        exe_mod.linkFramework("CoreGraphics", .{});
        exe_mod.linkFramework("Carbon", .{});
    } else if (os_tag == .windows) {
        exe_mod.linkSystemLibrary("user32", .{});
        exe_mod.linkSystemLibrary("gdi32", .{});
        exe_mod.linkSystemLibrary("kernel32", .{});
        exe_mod.linkSystemLibrary("shell32", .{});
        exe_mod.linkSystemLibrary("imm32", .{});
    }

    // Embedded: stb_truetype (compiled from vendored source)
    exe_mod.addCSourceFile(.{
        .file = b.path("vendor/stb_truetype.c"),
        .flags = &.{"-DSTB_TRUETYPE_IMPLEMENTATION"},
    });
    exe_mod.addIncludePath(b.path("vendor"));

    const exe = b.addExecutable(.{
        .name = "teru",
        .root_module = exe_mod,
    });
    b.installArtifact(exe);

    // ── run step ─────────────────────────────────────────────────────
    const run_cmd = b.addRunArtifact(exe);
    run_cmd.step.dependOn(b.getInstallStep());
    if (b.args) |args| {
        run_cmd.addArgs(args);
    }
    const run_step = b.step("run", "Run teru terminal");
    run_step.dependOn(&run_cmd.step);

    // ── bench (vtebench-style throughput harness) ────────────────────
    // `zig build bench -- tools/bench-payloads` runs teru's VT pipeline on
    // pre-captured payloads and prints JSON to stdout. See docs/BENCHMARKS.md.
    const bench_mod = b.createModule(.{
        .root_source_file = b.path("tools/bench.zig"),
        .target = target,
        .optimize = .ReleaseFast,
        .link_libc = true,
    });
    bench_mod.addImport("teru", lib_mod);
    const bench_exe = b.addExecutable(.{
        .name = "teru-bench",
        .root_module = bench_mod,
    });
    // Not installed into zig-out/bin by default; accessed via `zig build bench`.
    const bench_run = b.addRunArtifact(bench_exe);
    if (b.args) |args| bench_run.addArgs(args);
    const bench_step = b.step("bench", "Run the throughput benchmark harness (args: <payload-dir>)");
    bench_step.dependOn(&bench_run.step);

    // ── tests (pure Zig, no system deps needed) ──────────────────────
    const test_mod = b.createModule(.{
        .root_source_file = b.path("src/lib.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    test_mod.addOptions("build_options", build_options);
    const lib_tests = b.addTest(.{
        .root_module = test_mod,
    });
    const run_lib_tests = b.addRunArtifact(lib_tests);
    const test_step = b.step("test", "Run unit tests");
    test_step.dependOn(&run_lib_tests.step);

    // ── miozu compositor (optional, -Dcompositor=true) ────────────────
    if (enable_compositor and os_tag == .linux) {
        const miozu_mod = b.createModule(.{
            .root_source_file = b.path("src/compositor/main.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        });

        // Link libteru (lib_mod already carries build_options — don't add again)
        miozu_mod.addImport("teru", lib_mod);

        // wlroots and Wayland server deps
        miozu_mod.linkSystemLibrary("wlroots-0.18", .{});
        miozu_mod.linkSystemLibrary("wayland-server", .{});
        miozu_mod.linkSystemLibrary("xkbcommon", .{});
        miozu_mod.linkSystemLibrary("pixman-1", .{});
        // libinput for per-device tap-to-click / natural-scroll / DWT
        // config. wlroots' DRM+libinput backend already transitively
        // pulls this in at runtime; we link explicitly so the
        // libinput_device_config_* symbols resolve at link time.
        miozu_mod.linkSystemLibrary("input", .{});

        // stb_truetype for terminal pane rendering
        miozu_mod.addCSourceFile(.{
            .file = b.path("vendor/stb_truetype.c"),
            .flags = &.{"-DSTB_TRUETYPE_IMPLEMENTATION"},
        });
        miozu_mod.addIncludePath(b.path("vendor"));

        // wlroots signal accessor glue (safe C → Zig bridge for struct fields)
        // Needs vendor/ for xdg-shell-protocol.h (used by wlr_xdg_shell.h)
        miozu_mod.addCSourceFile(.{
            .file = b.path("vendor/miozu-wlr-glue.c"),
            .flags = &.{"-DWLR_USE_UNSTABLE"},
        });

        const miozu_exe = b.addExecutable(.{
            .name = "teruwm",
            .root_module = miozu_mod,
        });
        b.installArtifact(miozu_exe);

        const miozu_run = b.addRunArtifact(miozu_exe);
        miozu_run.step.dependOn(b.getInstallStep());
        if (b.args) |args| {
            miozu_run.addArgs(args);
        }
        const miozu_run_step = b.step("run-wm", "Run teruwm compositor");
        miozu_run_step.dependOn(&miozu_run.step);

        // Compositor tests — mirrors miozu_mod's link setup because
        // Node.zig / Bar.zig pull in wlr.zig types even in pure-math
        // code paths. Barrel is src/compositor/tests.zig; add files
        // there as their tests warrant it.
        const wm_test_mod = b.createModule(.{
            .root_source_file = b.path("src/compositor/tests.zig"),
            .target = target,
            .optimize = optimize,
            .link_libc = true,
        });
        wm_test_mod.addImport("teru", lib_mod);
        wm_test_mod.linkSystemLibrary("wlroots-0.18", .{});
        wm_test_mod.linkSystemLibrary("wayland-server", .{});
        wm_test_mod.linkSystemLibrary("xkbcommon", .{});
        wm_test_mod.linkSystemLibrary("pixman-1", .{});
        wm_test_mod.addCSourceFile(.{
            .file = b.path("vendor/stb_truetype.c"),
            .flags = &.{"-DSTB_TRUETYPE_IMPLEMENTATION"},
        });
        wm_test_mod.addIncludePath(b.path("vendor"));
        wm_test_mod.addCSourceFile(.{
            .file = b.path("vendor/miozu-wlr-glue.c"),
            .flags = &.{"-DWLR_USE_UNSTABLE"},
        });

        const wm_tests = b.addTest(.{ .root_module = wm_test_mod });
        const run_wm_tests = b.addRunArtifact(wm_tests);
        test_step.dependOn(&run_wm_tests.step);
    }

    // ── check step (compile lib only, no linking/frameworks needed) ──
    // Useful for cross-platform CI: `zig build check -Dtarget=x86_64-macos`
    const check_mod = b.createModule(.{
        .root_source_file = b.path("src/lib.zig"),
        .target = target,
        .optimize = optimize,
        .link_libc = true,
    });
    check_mod.addOptions("build_options", build_options);
    const check_lib = b.addLibrary(.{
        .name = "teru-check",
        .root_module = check_mod,
    });
    const check_step = b.step("check", "Compile lib for target (no linking)");
    check_step.dependOn(&check_lib.step);
}
